# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AirBV CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'   
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: create database in mysql-server
      run: mysql -uroot -h127.0.0.1 < src/sql/create-airbvdb.sql  
    - name: compile the code
      run: mvn clean compile
    - name: Create Datanucleus schema
      run: mvn datanucleus:schema-create
    - name: Launch the server in background mode 
      run: mvn jetty:run &
    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: Test with Maven
      run: mvn test -DargLine="-Dcontiperf.active=false"
    - name: Install doxygen
      run: sudo apt-get install -y doxygen
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    - name: Generate documentation
      run: mvn doxygen:report
      run: cd target/doxygen/latex
      run: make
      run: cd ../../..
    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: docs/doxygen/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
