# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AirBV CI with Maven

language: java
os: linux
jdk:
    - openjdk8
script:
    - mvn test -DargLine="-Dcontiperf.active=false"

branches:
    only:
        - development_junit
    except:
        - master
        - development
